export const firstNames = [
    "Davis", "Judy",
    "Randy", "Jane",
    "Peter", "Angela",
    "Bobby", "Jennifer",
    "Luke", "Ashley",
    "Ted", "Shannon",
    "John", "Sophie",
    "Ken", "Desiree",
    "Wesley", "Camille",
    "Clyde", "Helen",
    "Ramon", "Terra",
    "Collin", "Andrea",
    "Ralph", "Chloe",
    "Frank", "Kim",
    "Marcos", "Rebecca",
    "Patrick", "Samantha",
    "Ryan", "Amber",
    "Brandon", "Vanessa",
    "Aaron", "Rachel",
    "Gunner", "Megan",
    "Harold", "Lily",
    "Miles", "Mia",
    "Kayson", "Jessica",
    "Mitch", "Emma"
];

export const lastNames = [
    "Smith", "Johnson",
    "Williams", "Brown",
    "Jones", "Miller",
    "Davis", "Garcia",
    "Rodriguez", "Wilson",
    "Martinez", "Anderson",
    "Taylor", "Thomas",
    "Hernandez", "Moore",
    "Martin", "Jackson",
    "Thompson", "White",
    "Lopez", "Lee",
    "Gonzalez", "Harris",
    "Clark", "Lewis",
    "Robinson", "Walker",
    "Perez", "Hall",
    "Davis", "Garcia",
    "Young", "Allen",
    "Sanchez", "Wright",
    "King", "Scott",
    "Green", "Baker",
    "Adams", "Nelson",
    "Hill", "Ramirez",
    "Campbell", "Mitchell"
];